### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by jpg1003** [jpg1003/go-bees#1]

**Comment by DonFinidi** [comment]
José Luis actualizo dependencias. Principalmente MariaDB y PHP a 7.3 que son requisitos indispensables.

Haré copia de seguridad antes.

**Comment by jpg1003** [comment]
Perfecto muchas gracias, si necesitas ayuda comentame

**Comment by DonFinidi** [comment]
Actualizadas, verifica que todo sigue funcionando correctamente tras reiniciar el servicio.
