### ISSUE TITLE
Mejorar vistas para tablets

### ISSUE THREAD

**Issue by jpg1003** [jpg1003/go-bees#11]

**Comment by jpg1003** [comment]
Me pongo con esta tarea que creo que tengo una idea buena para que las vistas sean mas amigables

**Comment by DonFinidi** [comment]
Vale! Se usó Bootstrap para el diseño inicial así que lo que modifiques asegúrate de que también se hace siguiendo su manual

**Comment by jpg1003** [comment]
Podeis revisar con el equipo de NXOS el diseño??

**Comment by DonFinidi** [comment]
Perfecto. La cierro!
