### ISSUE TITLE
Config de grabación específica a la colmena

### ISSUE THREAD

**Issue by jpg1003** [jpg1003/go-bees#19]

**Comment by jpg1003** [comment]
Tengo alguna idea para optimizar y comprimir los datos de la grabacion, voy a ello

**Comment by DonFinidi** [comment]
Perfecto, se requería usar el códec H264!

**Comment by jpg1003** [comment]
Es necesario que se de el visto bueno para la compresion de datos de video

**Comment by DonFinidi** [comment]
Buen trabajo José Luis. He estado testeando y analizando datos y hemos obtenido una reducción media de tamaño del 63%.
