### ISSUE TITLE
Update OpenCV to 3.3

### ISSUE THREAD

**Issue by jpg1003** [jpg1003/go-bees#2]

**Comment by DonFinidi** [comment]
Actualizo OpenCV a la versión 3.3. Es una minor update, no debería haber problema.

**Comment by jpg1003** [comment]
Perfecto, Gracias!!

**Comment by DonFinidi** [comment]
Actualizada correctamente, igual que ya hice con las dependencias. Testea que todo funciona correctamente y que las llamadas a la API siguen funcionando bien.

**Comment by jpg1003** [comment]
Se revisa, todo funciona correctamente

**Comment by DonFinidi** [comment]
Cerrada pues!
