### ISSUE TITLE
Translate website to English

### ISSUE THREAD

**Issue by jpg1003** [jpg1003/go-bees#5]

**Comment by DonFinidi** [comment]
Le paso el XML con el contenido a traducir a Jason Richmond que es el traductor que han elegido para el proyecto.

**Comment by jpg1003** [comment]
Ya nos ha pasado la traduccion lo paso a Preview para que lo acepten

**Comment by DonFinidi** [comment]
Le han dado el visto el bueno en dirección en calidad. La cerramos.
